version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: digital-cart-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital_cart
      MYSQL_USER: digital
      MYSQL_PASSWORD: digitalcart
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - digital-network

  app:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: digital-cart-app
    volumes:
      - ./src:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/docker-php-custom.ini:ro
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - digital-network      

  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    container_name: digital-cart-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - digital-network      
volumes:
  mysql-data:
networks: 
  digital-network:
    driver: bridge